In [1]:
#Series的字符串表现形式为：索引在左边，值在右边。
import pandas as pd # type: ignore
import numpy as np # type: ignore
s = pd.Series([1,3,6,11,44,1])
print(s)
print('------------------------------------')

#DataFrame是一个表格型的数据结构，它包含有一组有序的列，每列可以是不同的值类型（数值，字符串，布尔值等）
#DataFrame既有行索引也有列索引， 它可以被看做由Series组成的大字典。
dates = pd.date_range('20160101',periods=6)
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=['a','b','c','d'])
print(df)
print('------------------------------------')
print(df['b'])
print('------------------------------------')
print(df.dtypes)
print('------------------------------------')
print(df.index)
print('------------------------------------')
print(df.columns)
print('------------------------------------')
print(df.values)
print('------------------------------------')
df.describe()
print('------------------------------------')
print(df.T) #翻转数据
print('------------------------------------')
print(df.sort_index(axis=1, ascending=False)) #按照index排序
print('------------------------------------')
print(df.sort_values(by='a')) #按值排序
print('------------------------------------')
#选择数据
dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.arange(24).reshape((6,4)),index=dates, columns=['A','B','C','D'])
print(df)
print('------------------------------------')
print(df['A'])
print('------------------------------------')
print(df.A)
print('------------------------------------')
#选择行
print(df[0:3])
print('------------------------------------')
#使用标签来选择数据 loc
print(df.loc['20130102'])
print(df.loc[:,['A','B']]) 
print(df.loc['20130102',['A','B']])
print('------------------------------------')
#采用位置进行选择 iloc
print(df.iloc[3,1])
print(df.iloc[3:5,1:3])
print(df.iloc[[1,3,5],1:3])
print('------------------------------------')
#判断指令 (Boolean indexing) 进行选择
print(df[df.A>8])
print('------------------------------------')
# 创建数据
dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.arange(24).reshape((6,4)),index=dates, columns=['A','B','C','D'])
print(df)
print('------------------------------------')
#利用索引或者标签确定需要修改值的位置
df.iloc[2,2] = 1111
df.loc['20130101','B'] = 2222
print(df)
print('------------------------------------')
#根据条件 如果现在的判断条件是这样, 我们想要更改B中的数, 而更改的位置是取决于 A 的. 对于A大于4的位置. 更改B在相应位置上的数为0.
df.B[df.A>4] = 0
print(df)
print('------------------------------------')
#批量处理
df['F'] = np.nan
print(df)
print('------------------------------------')
dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.arange(24).reshape((6,4)),index=dates, columns=['A','B','C','D'])
df.iloc[0,1] = np.nan
df.iloc[1,2] = np.nan
print('------------------------------------')
#直接去掉有 NaN 的行或列, 可以使用 dropna
df.dropna(
    axis=0,     # 0: 对行进行操作; 1: 对列进行操作
    how='any'   # 'any': 只要存在 NaN 就 drop 掉; 'all': 必须全部是 NaN 才 drop 
    ) 
print('------------------------------------')
#将 NaN 的值用其他值代替, 比如代替成 0
df.fillna(value=0)
print('------------------------------------')
#判断是否有缺失数据 NaN, 为 True 表示缺失数据
df.isnull() 
print('------------------------------------')

0     1
1     3
2     6
3    11
4    44
5     1
dtype: int64
------------------------------------
                   a         b         c         d
2016-01-01 -0.490271 -0.729583 -0.551969 -0.105043
2016-01-02  1.146247  0.979273 -2.402041  2.410641
2016-01-03 -2.596550  1.496817 -0.026128  1.197802
2016-01-04  0.554654  0.515805 -0.023203 -1.248793
2016-01-05 -0.033446  0.341072  0.743270  0.213266
2016-01-06 -0.816741 -1.071473 -2.308192 -0.940361
------------------------------------
2016-01-01   -0.729583
2016-01-02    0.979273
2016-01-03    1.496817
2016-01-04    0.515805
2016-01-05    0.341072
2016-01-06   -1.071473
Freq: D, Name: b, dtype: float64
------------------------------------
a    float64
b    float64
c    float64
d    float64
dtype: object
------------------------------------
DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06'],
              dtype='datetime64[ns]', freq='D')
------------------------------------
Index(['a', 'b', 'c', 'd'], dtype='object')
------------------------------------
[[-0.49027058 -0.72958287 -0.55196854 -0.10504283]
 [ 1.14624742  0.97927314 -2.40204065  2.41064095]
 [-2.59655045  1.49681693 -0.02612793  1.19780158]
 [ 0.5546541   0.51580458 -0.02320327 -1.24879296]
 [-0.0334459   0.34107151  0.74327005  0.21326585]
 [-0.81674111 -1.07147324 -2.30819215 -0.94036121]]
------------------------------------
------------------------------------
   2016-01-01  2016-01-02  2016-01-03  2016-01-04  2016-01-05  2016-01-06
a   -0.490271    1.146247   -2.596550    0.554654   -0.033446   -0.816741
b   -0.729583    0.979273    1.496817    0.515805    0.341072   -1.071473
c   -0.551969   -2.402041   -0.026128   -0.023203    0.743270   -2.308192
d   -0.105043    2.410641    1.197802   -1.248793    0.213266   -0.940361
------------------------------------
                   d         c         b         a
2016-01-01 -0.105043 -0.551969 -0.729583 -0.490271
2016-01-02  2.410641 -2.402041  0.979273  1.146247
2016-01-03  1.197802 -0.026128  1.496817 -2.596550
2016-01-04 -1.248793 -0.023203  0.515805  0.554654
2016-01-05  0.213266  0.743270  0.341072 -0.033446
2016-01-06 -0.940361 -2.308192 -1.071473 -0.816741
------------------------------------
                   a         b         c         d
2016-01-03 -2.596550  1.496817 -0.026128  1.197802
2016-01-06 -0.816741 -1.071473 -2.308192 -0.940361
2016-01-01 -0.490271 -0.729583 -0.551969 -0.105043
2016-01-05 -0.033446  0.341072  0.743270  0.213266
2016-01-04  0.554654  0.515805 -0.023203 -1.248793
2016-01-02  1.146247  0.979273 -2.402041  2.410641
------------------------------------
             A   B   C   D
2013-01-01   0   1   2   3
2013-01-02   4   5   6   7
2013-01-03   8   9  10  11
2013-01-04  12  13  14  15
2013-01-05  16  17  18  19
2013-01-06  20  21  22  23
------------------------------------
2013-01-01     0
2013-01-02     4
2013-01-03     8
2013-01-04    12
2013-01-05    16
2013-01-06    20
Freq: D, Name: A, dtype: int32
------------------------------------
2013-01-01     0
2013-01-02     4
2013-01-03     8
2013-01-04    12
2013-01-05    16
2013-01-06    20
Freq: D, Name: A, dtype: int32
------------------------------------
            A  B   C   D
2013-01-01  0  1   2   3
2013-01-02  4  5   6   7
2013-01-03  8  9  10  11
------------------------------------
A    4
B    5
C    6
D    7
Name: 2013-01-02 00:00:00, dtype: int32
             A   B
2013-01-01   0   1
2013-01-02   4   5
2013-01-03   8   9
2013-01-04  12  13
2013-01-05  16  17
2013-01-06  20  21
A    4
B    5
Name: 2013-01-02 00:00:00, dtype: int32
------------------------------------
13
             B   C
2013-01-04  13  14
2013-01-05  17  18
             B   C
2013-01-02   5   6
2013-01-04  13  14
2013-01-06  21  22
------------------------------------
             A   B   C   D
2013-01-04  12  13  14  15
2013-01-05  16  17  18  19
2013-01-06  20  21  22  23
------------------------------------
             A   B   C   D
2013-01-01   0   1   2   3
2013-01-02   4   5   6   7
2013-01-03   8   9  10  11
2013-01-04  12  13  14  15
2013-01-05  16  17  18  19
2013-01-06  20  21  22  23
------------------------------------
             A     B     C   D
2013-01-01   0  2222     2   3
2013-01-02   4     5     6   7
2013-01-03   8     9  1111  11
2013-01-04  12    13    14  15
2013-01-05  16    17    18  19
2013-01-06  20    21    22  23
------------------------------------
             A     B     C   D
2013-01-01   0  2222     2   3
2013-01-02   4     5     6   7
2013-01-03   8     0  1111  11
2013-01-04  12     0    14  15
2013-01-05  16     0    18  19
2013-01-06  20     0    22  23
------------------------------------
             A     B     C   D   F
2013-01-01   0  2222     2   3 NaN
2013-01-02   4     5     6   7 NaN
2013-01-03   8     0  1111  11 NaN
2013-01-04  12     0    14  15 NaN
2013-01-05  16     0    18  19 NaN
2013-01-06  20     0    22  23 NaN
------------------------------------
------------------------------------
------------------------------------
------------------------------------
------------------------------------

C:\Users\10075\AppData\Local\Temp\ipykernel_9008\726745109.py:68: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df.B[df.A>4] = 0